# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
# source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
workspace 'Nanameue.xcworkspace'

def shared_pods
  use_frameworks!
 
  pod 'SwiftLint', '0.40.3'
  pod 'Firebase', '7.8.0'
  pod 'FirebaseAuth', '7.11.0'
  pod 'FirebaseFirestore', '7.9.0'
  pod 'Firebase/Database', '7.8.0'
  pod 'Firebase/Storage', '7.8.0'
end

target 'Nanameue' do
  shared_pods
end

target 'NanameueTests' do
  shared_pods
end
