# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
# source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
workspace 'Nanameue.xcworkspace'

def shared_pods
  use_frameworks!
 
  pod 'SwiftLint', '0.40.3'
  pod 'Firebase'
  pod 'Firebase/Analytics', '7.8.1'
  pod 'Firebase/Crashlytics', '7.8.1'
  pod 'Firebase/RemoteConfig'
end

target 'Nanameue' do
  shared_pods
end

target 'NanameueTests' do
  shared_pods
end
